services:
  bot:
    build: .
    container_name: yandex_lyceum_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/app/data/bot_stats.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs